{
"project_name" : "RTSP AI Detection System",
"author": "Prakash pacharne",
"mode" : "rtsp",
"image_size" : 640,
"classes" : 0,
"persist" : "True",
"conf_threshold" : 0.2,
"resize_width" : 640,
"resize_height": 640,
"normalize_frames" : "True",
"log_file_path" : "assets/rtsp_detection.log",
"pretrained_model_pt_path" : "assets/yolov9t.pt",
"pretrained_model_onnx_path" : "assets/yolov9t.onnx",
"rtsp_link" : "rtsp://your_username:your_password@your_camera_ip:554/your_stream_path",
"inference_video" : "assets/sleeping.webm",
"roi_points" : "assets/roi_points.txt",
"verbose_history" : 0,
"iou_threshold": 0.3,
"dis_lines" : "y",
"idle_alert_threshold" : 10,
"movement_threshold" : 2.5,
"rtsp_reconnect_attempts" : 5,
"rtsp_reconnect_delay" : 2.0,
"rtsp_buffer_size" : 1,
"rtsp_timeout" : 30
}
